<?php
if (!defined('ABSPATH')) {
    exit;
}

function goodjob_ai_site_admin_menu() {
    add_menu_page(
        'GoodJob AI Site',
        'GoodJob AI Site',
        'manage_options',
        'goodjob-ai-site',
        'goodjob_ai_site_admin_page',
        'dashicons-admin-site-alt3',
        58
    );
}
add_action('admin_menu', 'goodjob_ai_site_admin_menu');

function goodjob_ai_site_admin_page() {
    if (!current_user_can('manage_options')) {
        return;
    }
    $options = goodjob_ai_site_read_json('_data/site-options.json');
    $collections = goodjob_ai_site_read_json('_data/collections.json');
    echo '<div class="wrap"><h1>GoodJob AI Site</h1>';
    echo '<p>This page is generated by GoodJob. It shows the imported site options, seed collections, and install status.</p>';
    echo '<p><strong>Last seeded:</strong> ' . esc_html(get_option('goodjob_ai_site_seeded_at', 'Not seeded yet')) . '</p>';
    echo '<form method="post" action="' . esc_url(admin_url('admin-post.php')) . '">';
    wp_nonce_field('goodjob_ai_site_reseed');
    echo '<input type="hidden" name="action" value="goodjob_ai_site_reseed">';
    submit_button('Rebuild Pages and Seed Data');
    echo '</form>';
    echo '<h2>Site Options</h2><pre style="max-height:280px;overflow:auto;background:#fff;padding:16px;border:1px solid #ccd0d4;">' . esc_html(wp_json_encode($options, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)) . '</pre>';
    echo '<h2>Collections</h2><pre style="max-height:360px;overflow:auto;background:#fff;padding:16px;border:1px solid #ccd0d4;">' . esc_html(wp_json_encode($collections, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)) . '</pre>';
    echo '</div>';
}

function goodjob_ai_site_handle_reseed() {
    if (!current_user_can('manage_options')) {
        wp_die('Permission denied');
    }
    check_admin_referer('goodjob_ai_site_reseed');
    goodjob_ai_site_seed_all(true);
    wp_safe_redirect(admin_url('admin.php?page=goodjob-ai-site&seeded=1'));
    exit;
}
add_action('admin_post_goodjob_ai_site_reseed', 'goodjob_ai_site_handle_reseed');
